---

- name: Install CernVM-FS local proxy dependencies (yum)
  yum:
    name: "{{ item }}"
  with_items:
    - nginx
  when: ansible_os_family == "RedHat"

- name: Install CernVM-FS local proxy dependencies (apt)
  apt:
    name: "{{ item }}"
  with_items:
    - nginx
  when: ansible_os_family == "Debian"

- name: Configure squid for local proxies
  template:
    src: localproxy_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/squid.conf
    backup: yes
  notify:
    - restart squid

- name: Ensure nginx is enabled and running
  service:
    name: nginx
    state: started
    enabled: yes
