---

- name: Install CernVM-FS local proxy dependencies (yum)
  yum:
    name: "{{ item }}"
  with_items:
    - nginx
  when: ansible_os_family == "RedHat"

- name: Install CernVM-FS local proxy dependencies (apt)
  apt:
    name: "{{ item }}"
  with_items:
    - nginx
  when: ansible_os_family == "Debian"

# Need to double check that this actually works (see the hosts_file directive)
#- name: Create squid hosts file
#  copy:
#    content: |
#      {{ inventory_hostname }} 127.0.0.1
#    dest: /etc/squid/hosts
#  notify:
#    - restart squid

- name: Configure squid for local proxies
  template:
    src: localproxy_nginx.conf.j2
    dest: /etc/nginx/sites-enabled/squid.conf
    backup: yes
  notify:
    - restart squid

- name: Ensure nginx is enabled and running
  service:
    name: nginx
    state: started
    enabled: yes
